[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@flarenetwork/flare-periphery-contracts=lib/flare-foundry-periphery-package/src", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
